'use client';

import { DietPlan } from '@/lib/types';
import { Page, Text, Document, StyleSheet, PDFDownloadLink, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#fff',
    padding: 30,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    marginBottom: 10,
    color: '#333',
  },
  macros: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#f5f5f5',
  },
  macroText: {
    fontSize: 12,
    marginBottom: 5,
  },
  meal: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#f8f8f8',
  },
  mealTitle: {
    fontSize: 16,
    marginBottom: 5,
  },
  mealTime: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  mealItem: {
    marginBottom: 8,
    paddingLeft: 10,
  },
  itemName: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  itemDetails: {
    fontSize: 10,
    color: '#666',
  },
  recommendations: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f5f5f5',
  },
  recommendationTitle: {
    fontSize: 16,
    marginBottom: 10,
  },
  recommendationItem: {
    fontSize: 12,
    marginBottom: 5,
    color: '#666',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#666',
    fontSize: 10,
  },
});

interface DietPDFProps {
  dietPlan: DietPlan;
}

const DietPDF = ({ dietPlan }: DietPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Your Personalized Diet Plan</Text>

      <View style={styles.macros}>
        <Text style={styles.sectionTitle}>Daily Targets</Text>
        <Text style={styles.macroText}>Total Calories: {dietPlan.dailyCalories} kcal</Text>
        <Text style={styles.macroText}>Protein: {dietPlan.macronutrients.protein}g</Text>
        <Text style={styles.macroText}>Carbohydrates: {dietPlan.macronutrients.carbs}g</Text>
        <Text style={styles.macroText}>Fats: {dietPlan.macronutrients.fats}g</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Meal Plan</Text>
        {dietPlan.mealPlan.map((meal, index) => (
          <View key={index} style={styles.meal}>
            <Text style={styles.mealTitle}>{meal.name}</Text>
            <Text style={styles.mealTime}>{meal.time} - {meal.calories} kcal</Text>
            
            {meal.items.map((item, itemIndex) => (
              <View key={itemIndex} style={styles.mealItem}>
                <Text style={styles.itemName}>{item.name}</Text>
                <Text style={styles.itemDetails}>
                  Portion: {item.portion} | Calories: {item.calories} kcal
                </Text>
                <Text style={styles.itemDetails}>
                  P: {item.protein}g | C: {item.carbs}g | F: {item.fats}g
                </Text>
                {item.notes && (
                  <Text style={styles.itemDetails}>Notes: {item.notes}</Text>
                )}
              </View>
            ))}
            
            {meal.notes && (
              <Text style={styles.itemDetails}>Meal Notes: {meal.notes}</Text>
            )}
          </View>
        ))}
      </View>

      <View style={styles.recommendations}>
        <Text style={styles.recommendationTitle}>Recommendations</Text>
        {dietPlan.recommendations.map((rec, index) => (
          <Text key={index} style={styles.recommendationItem}>• {rec}</Text>
        ))}
      </View>

      {dietPlan.supplements && dietPlan.supplements.length > 0 && (
        <View style={styles.recommendations}>
          <Text style={styles.recommendationTitle}>Recommended Supplements</Text>
          {dietPlan.supplements.map((supplement, index) => (
            <Text key={index} style={styles.recommendationItem}>• {supplement}</Text>
          ))}
        </View>
      )}

      {dietPlan.restrictions && dietPlan.restrictions.length > 0 && (
        <View style={styles.recommendations}>
          <Text style={styles.recommendationTitle}>Foods to Avoid</Text>
          {dietPlan.restrictions.map((restriction, index) => (
            <Text key={index} style={styles.recommendationItem}>• {restriction}</Text>
          ))}
        </View>
      )}

      <Text style={styles.footer}>
        Generated by FitAI - Your Personal AI Nutritionist
      </Text>
    </Page>
  </Document>
);

export function DownloadDietPDFButton({ dietPlan }: DietPDFProps) {
  return (
    <PDFDownloadLink
      document={<DietPDF dietPlan={dietPlan} />}
      fileName="personalized-diet-plan.pdf"
      className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full"
    >
      Download Complete Diet Plan (PDF)
    </PDFDownloadLink>
  );
}