'use client';

import { WorkoutPlan } from '@/lib/types';
import { Page, Text, Document, StyleSheet, PDFDownloadLink, View, BlobProvider } from '@react-pdf/renderer';
import type { PDFDownloadLinkProps } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#fff',
    padding: 30,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    marginBottom: 10,
    color: '#333',
  },
  routineTitle: {
    fontSize: 16,
    marginTop: 15,
    marginBottom: 10,
    backgroundColor: '#f5f5f5',
    padding: 8,
  },
  routineInfo: {
    fontSize: 12,
    marginBottom: 10,
    color: '#666',
  },
  exercise: {
    marginBottom: 12,
    padding: 8,
    backgroundColor: '#f8f8f8',
  },
  exerciseName: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  exerciseDetails: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
  },
  exerciseNotes: {
    fontSize: 11,
    color: '#666',
    marginTop: 5,
    fontStyle: 'italic',
  },
  recommendations: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f5f5f5',
  },
  recommendationTitle: {
    fontSize: 16,
    marginBottom: 10,
  },
  recommendationItem: {
    fontSize: 12,
    marginBottom: 5,
    color: '#666',
  },
  weeklySchedule: {
    marginTop: 10,
    marginBottom: 20,
  },
  scheduleItem: {
    fontSize: 12,
    marginBottom: 5,
    color: '#666',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#666',
    fontSize: 10,
  },
});

interface WorkoutPDFProps {
  workoutPlan: WorkoutPlan;
}

const WorkoutPDF = ({ workoutPlan }: WorkoutPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Your Complete Workout Plan</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Weekly Schedule</Text>
        {workoutPlan.weeklySchedule.map((day, index) => (
          <Text key={index} style={styles.scheduleItem}>
            • {day}
          </Text>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Detailed Workout Routines</Text>
        {workoutPlan.routines.map((routine, index) => (
          <View key={index}>
            <Text style={styles.routineTitle}>{routine.day}</Text>
            <Text style={styles.routineInfo}>
              Duration: {routine.duration} minutes | Intensity: {routine.intensity}
            </Text>

            {routine.exercises.map((exercise, exerciseIndex) => (
              <View key={exerciseIndex} style={styles.exercise}>
                <Text style={styles.exerciseName}>{exercise.name}</Text>
                <Text style={styles.exerciseDetails}>
                  Sets: {exercise.sets} | Reps: {exercise.reps}
                </Text>
                <Text style={styles.exerciseDetails}>
                  Rest between sets: {exercise.restTime} seconds
                </Text>
                {exercise.notes && (
                  <Text style={styles.exerciseNotes}>Form tips: {exercise.notes}</Text>
                )}
              </View>
            ))}
          </View>
        ))}
      </View>

      <View style={styles.recommendations}>
        <Text style={styles.recommendationTitle}>Training Recommendations</Text>
        {workoutPlan.recommendations.map((rec, index) => (
          <Text key={index} style={styles.recommendationItem}>
            • {rec}
          </Text>
        ))}
      </View>

      <Text style={styles.footer}>
        Generated by FitAI - Your Personal AI Trainer
      </Text>
    </Page>
  </Document>
);

export function DownloadPDFButton({ workoutPlan }: WorkoutPDFProps) {
  return (
    <PDFDownloadLink
      document={<WorkoutPDF workoutPlan={workoutPlan} />}
      fileName="complete-workout-plan.pdf"
      className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full"
    >
      {/* Using a regular ReactNode instead of a render prop */}
      Download Complete Workout Plan (PDF)
    </PDFDownloadLink>
  );
}